apiVersion: batch/v1
kind: CronJob
metadata:
    labels:
        app: file-appender
        managed-by: harness
        release: release-bb45d0e5-2957-32ab-a9cc-a1936aeb268c
        releaseNumber: "79"
    name: file-appender-batch
    namespace: ms-savings-cdb
spec:
    schedule: '50 15 * * *'
    suspend: false
    successfulJobsHistoryLimit: 50
    failedJobsHistoryLimit: 50
    concurrencyPolicy: Forbid
    jobTemplate:
        spec:
            activeDeadlineSeconds: 43200
            parallelism: 50
            template:
                metadata:
                    annotations:
                        sidecar.istio.io/inject: "false"
                spec:
                    dnsPolicy: ClusterFirst
                    restartPolicy: OnFailure
                    schedulerName: default-scheduler
                    terminationGracePeriodSeconds: 30
                    containers:
                        -   name: file-appender-batch
                            image: fernandotaa/file-appender-batch:2
                            imagePullPolicy: IfNotPresent
                            command: [ "/bin/bash" ]
                            args:
                                - -c
                                - >
                                    export CUSTOM_HOST_NAME=$HOSTNAME;
                                    java -jar /app.jar;
                            env:
                                -   name: FILE_DIRECTORY
                                    value: "/shared/"
                                -   name: RUN_UTIL
                                    value: "1000000"
                            volumeMounts:
                                -   name: file-appender-volume
                                    mountPath: /shared
                    volumes:
                        -   name: file-appender-volume
                            persistentVolumeClaim:
                                claimName: file-appender-batch

